import Dexie, { Table } from 'dexie';
import dexieCloud, { DexieCloudTable } from 'dexie-cloud-addon';
import { populate } from './populate';
import { TodoItem } from './TodoItem';
import { TodoList } from './TodoList';

export class TodoDB extends Dexie {
  // Table accessors are auto-generated by Dexie (from schema below)
  todoLists!: DexieCloudTable<TodoList, 'id'>;
  todoItems!: DexieCloudTable<TodoItem, 'id'>;
  openCloseStates!: Table<boolean, [string, string]>;

  constructor() {
    super('TodoDBCloud2', {
      addons: [dexieCloud],
      cache: "immutable"
    });
    this.version(14).stores({
      todoLists: `@id`,
      todoItems: `@id, [todoListId+realmId]`,
      openCloseStates: `` // Set of open ids (persisted local state only)
    });
    this.todoLists.mapToClass(TodoList);
    this.on('populate', () => {
      this.on('ready', () => {
        return populate(this);
      });
    });
    // Configure cloud:
    this.cloud.configure({
      unsyncedTables: ['openCloseStates'],
      databaseUrl: process.env.REACT_APP_DBURL!,
      tryUseServiceWorker: true, // true!
      requireAuth: false,
    });
  }
}
