import Dexie, { Table } from 'dexie';
import dexieCloud, { DexieCloudTable } from 'dexie-cloud-addon';
import { usePermissions } from 'dexie-react-hooks';
import { TodoItem } from './TodoItem';
import { TodoList } from './TodoList';

export class TodoDB extends Dexie {
  // Table accessors are auto-generated by Dexie (from schema below)
  todoLists!: DexieCloudTable<TodoList, 'id'>;
  todoItems!: DexieCloudTable<TodoItem, 'id'>;

  constructor() {
    super('TodoDBCloud2', { addons: [dexieCloud] });
    this.version(10).stores({
      todoLists: `@id`,
      todoItems: `@id, [todoListId+realmId]`,
    });
    this.todoLists.mapToClass(TodoList);
  }
}
