import { IsStrictlyAny } from "./is-strictly-any";

/** Extract the union of literal method names in T
 */
 type NonInsertProps<T> = {
  [P in keyof T]: IsStrictlyAny<T[P]> extends true
    ? never // Plain property of type any (not method)
    : T[P] extends (...args: any[]) => any
    ? P // a function (method)
    : T[P] extends {on:any,subdocs:any,gc:any,isSynced:any,isLoaded:any,shouldLoad:any}
    ? P // an YDoc property - should be generated by dexie and not by user
    : never; // Not a non-insert property (don't omit it from InsertType)
}[keyof T];

/** Default insert type of T is a subset of T where:
 *    * given optional props (such as an auto-generated primary key) are made optional
 *    * methods are omitted
 */
 export type InsertType<T, OptionalProps extends keyof T> = Omit<T, OptionalProps | NonInsertProps<T>> & {[P in OptionalProps]?: T[P]};
